[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
deadman_switch = "5BR3iY7HKjy2qdL7i99bQZPP9fxAzpGAVcihR7MHZWj6"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
